name = "swagger"
version = "0.1.0"

description = "Gleam API wrapper for Forgejo's API (swagger)"
licences = ["BSD-3-Clause"]
repository = { type = "codeberg", user = "naomi", repo = "Swagger" }
links = [
  { title = "Website", href = "https://codeberg.org/api/swagger#/" },
  { title = "Sponsor", href = "https://ko-fi.com/naomieow" },
]

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_http = ">= 3.6.0 and < 4.0.0"
gleam_json = ">= 1.0.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
gleam_httpc = ">= 2.2.0 and < 3.0.0"
pprint = ">= 1.0.3 and < 2.0.0"
